[package]
name = "f2c"
version = "0.0.1"
description = "Fortran 2 c compiler"
readme = "README.md"
repository = "https://github.com/wapm-packages/f2c"

[[module]]
name = "f2c"
source = "f2c.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

# [[module]]
# name = "libcrypto"
# source = "libcrypto.wasm"

# [[module]]
# name = "libssl"
# source = "libssl.wasm"

[[command]]
name = "f2c"
module = "f2c"
